#!/bin/sh

# settings for common commands
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias ln="ln -v"
alias mkdir="mkdir -pv"
alias rmdir="rmdir -v"
alias ls="exa --icons --group-directories-first -la"
alias locate="plocate"
alias cat='bat'
alias grep='grep --color=always'

alias aura='sudo aura'
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias k='kubectl'
alias d='docker'
alias g='git'
alias blue='bluetoothctl'
alias lf='lfub'
alias npm='sudo npm'
alias cd='z'
